// Code generated by command: go run asm.go -out ../fq_amd64.s. DO NOT EDIT.

// +build amd64,!generic

// func fqAdd(z *[6]uint64, x *[6]uint64, y *[6]uint64)
TEXT ·fqAdd(SB), $0-24
	MOVQ    x+8(FP), AX
	MOVQ    y+16(FP), CX
	MOVQ    (AX), DX
	MOVQ    8(AX), BX
	MOVQ    16(AX), BP
	MOVQ    24(AX), SI
	MOVQ    32(AX), DI
	MOVQ    40(AX), AX
	ADDQ    (CX), DX
	ADCQ    8(CX), BX
	ADCQ    16(CX), BP
	ADCQ    24(CX), SI
	ADCQ    32(CX), DI
	ADCQ    40(CX), AX
	MOVQ    z+0(FP), CX
	MOVQ    DX, R8
	MOVQ    BX, R9
	MOVQ    BP, R10
	MOVQ    SI, R11
	MOVQ    DI, R12
	MOVQ    AX, R13
	SUBQ    ·q64+0(SB), R8
	SBBQ    ·q64+8(SB), R9
	SBBQ    ·q64+16(SB), R10
	SBBQ    ·q64+24(SB), R11
	SBBQ    ·q64+32(SB), R12
	SBBQ    ·q64+40(SB), R13
	CMOVQCC R8, DX
	CMOVQCC R9, BX
	CMOVQCC R10, BP
	CMOVQCC R11, SI
	CMOVQCC R12, DI
	CMOVQCC R13, AX
	MOVQ    DX, (CX)
	MOVQ    BX, 8(CX)
	MOVQ    BP, 16(CX)
	MOVQ    SI, 24(CX)
	MOVQ    DI, 32(CX)
	MOVQ    AX, 40(CX)
	RET

// func fqNeg(z *[6]uint64, x *[6]uint64)
TEXT ·fqNeg(SB), $0-16
	MOVQ    x+8(FP), DI
	MOVQ    ·q64+0(SB), AX
	MOVQ    ·q64+8(SB), CX
	MOVQ    ·q64+16(SB), DX
	MOVQ    ·q64+24(SB), BX
	MOVQ    ·q64+32(SB), BP
	MOVQ    ·q64+40(SB), SI
	SUBQ    (DI), AX
	SBBQ    8(DI), CX
	SBBQ    16(DI), DX
	SBBQ    24(DI), BX
	SBBQ    32(DI), BP
	SBBQ    40(DI), SI
	MOVQ    AX, DI
	MOVQ    CX, R8
	MOVQ    DX, R9
	MOVQ    BX, R10
	MOVQ    BP, R11
	MOVQ    SI, R12
	SUBQ    ·q64+0(SB), DI
	SBBQ    ·q64+8(SB), R8
	SBBQ    ·q64+16(SB), R9
	SBBQ    ·q64+24(SB), R10
	SBBQ    ·q64+32(SB), R11
	SBBQ    ·q64+40(SB), R12
	CMOVQCC DI, AX
	CMOVQCC R8, CX
	CMOVQCC R9, DX
	CMOVQCC R10, BX
	CMOVQCC R11, BP
	CMOVQCC R12, SI
	MOVQ    z+0(FP), DI
	MOVQ    AX, (DI)
	MOVQ    CX, 8(DI)
	MOVQ    DX, 16(DI)
	MOVQ    BX, 24(DI)
	MOVQ    BP, 32(DI)
	MOVQ    SI, 40(DI)
	RET

// func fqSub(z *[6]uint64, x *[6]uint64, y *[6]uint64)
TEXT ·fqSub(SB), $0-24
	MOVQ    y+16(FP), AX
	MOVQ    ·q64+0(SB), CX
	MOVQ    ·q64+8(SB), DX
	MOVQ    ·q64+16(SB), BX
	MOVQ    ·q64+24(SB), BP
	MOVQ    ·q64+32(SB), SI
	MOVQ    ·q64+40(SB), DI
	SUBQ    (AX), CX
	SBBQ    8(AX), DX
	SBBQ    16(AX), BX
	SBBQ    24(AX), BP
	SBBQ    32(AX), SI
	SBBQ    40(AX), DI
	MOVQ    CX, AX
	MOVQ    DX, R8
	MOVQ    BX, R9
	MOVQ    BP, R10
	MOVQ    SI, R11
	MOVQ    DI, R12
	SUBQ    ·q64+0(SB), AX
	SBBQ    ·q64+8(SB), R8
	SBBQ    ·q64+16(SB), R9
	SBBQ    ·q64+24(SB), R10
	SBBQ    ·q64+32(SB), R11
	SBBQ    ·q64+40(SB), R12
	CMOVQCC AX, CX
	CMOVQCC R8, DX
	CMOVQCC R9, BX
	CMOVQCC R10, BP
	CMOVQCC R11, SI
	CMOVQCC R12, DI
	MOVQ    x+8(FP), AX
	ADDQ    (AX), CX
	ADCQ    8(AX), DX
	ADCQ    16(AX), BX
	ADCQ    24(AX), BP
	ADCQ    32(AX), SI
	ADCQ    40(AX), DI
	MOVQ    z+0(FP), AX
	MOVQ    CX, R8
	MOVQ    DX, R9
	MOVQ    BX, R10
	MOVQ    BP, R11
	MOVQ    SI, R12
	MOVQ    DI, R13
	SUBQ    ·q64+0(SB), R8
	SBBQ    ·q64+8(SB), R9
	SBBQ    ·q64+16(SB), R10
	SBBQ    ·q64+24(SB), R11
	SBBQ    ·q64+32(SB), R12
	SBBQ    ·q64+40(SB), R13
	CMOVQCC R8, CX
	CMOVQCC R9, DX
	CMOVQCC R10, BX
	CMOVQCC R11, BP
	CMOVQCC R12, SI
	CMOVQCC R13, DI
	MOVQ    CX, (AX)
	MOVQ    DX, 8(AX)
	MOVQ    BX, 16(AX)
	MOVQ    BP, 24(AX)
	MOVQ    SI, 32(AX)
	MOVQ    DI, 40(AX)
	RET

// func fqMul(z *[6]uint64, x *[6]uint64, y *[6]uint64)
TEXT ·fqMul(SB), $96-24
	MOVQ    x+8(FP), CX
	MOVQ    y+16(FP), BP
	CMPB    ·hasBMI2+0(SB), $0x00
	JE      fallback
	MOVQ    (CX), DX
	MULXQ   (BP), SI, DI
	MULXQ   8(BP), AX, R8
	ADDQ    AX, DI
	ADCQ    $0x00, R8
	MULXQ   16(BP), AX, R9
	ADDQ    AX, R8
	ADCQ    $0x00, R9
	MULXQ   24(BP), AX, R10
	ADDQ    AX, R9
	ADCQ    $0x00, R10
	MULXQ   32(BP), AX, R11
	ADDQ    AX, R10
	ADCQ    $0x00, R11
	MULXQ   40(BP), AX, BX
	ADDQ    AX, R11
	ADCQ    $0x00, BX
	MOVQ    BX, 48(SP)
	MOVQ    SI, (SP)
	MOVQ    DI, 8(SP)
	MOVQ    R8, 16(SP)
	MOVQ    R9, 24(SP)
	MOVQ    R10, 32(SP)
	MOVQ    R11, 40(SP)
	MOVQ    8(CX), DX
	MULXQ   (BP), SI, DI
	MULXQ   8(BP), AX, R8
	ADDQ    AX, DI
	ADCQ    $0x00, R8
	MULXQ   16(BP), AX, R9
	ADDQ    AX, R8
	ADCQ    $0x00, R9
	MULXQ   24(BP), AX, R10
	ADDQ    AX, R9
	ADCQ    $0x00, R10
	MULXQ   32(BP), AX, R11
	ADDQ    AX, R10
	ADCQ    $0x00, R11
	MULXQ   40(BP), AX, BX
	ADDQ    AX, R11
	ADCQ    $0x00, BX
	ADDQ    8(SP), SI
	ADCQ    16(SP), DI
	ADCQ    24(SP), R8
	ADCQ    32(SP), R9
	ADCQ    40(SP), R10
	ADCQ    48(SP), R11
	ADCQ    $0x00, BX
	MOVQ    BX, 56(SP)
	MOVQ    SI, 8(SP)
	MOVQ    DI, 16(SP)
	MOVQ    R8, 24(SP)
	MOVQ    R9, 32(SP)
	MOVQ    R10, 40(SP)
	MOVQ    R11, 48(SP)
	MOVQ    16(CX), DX
	MULXQ   (BP), SI, DI
	MULXQ   8(BP), AX, R8
	ADDQ    AX, DI
	ADCQ    $0x00, R8
	MULXQ   16(BP), AX, R9
	ADDQ    AX, R8
	ADCQ    $0x00, R9
	MULXQ   24(BP), AX, R10
	ADDQ    AX, R9
	ADCQ    $0x00, R10
	MULXQ   32(BP), AX, R11
	ADDQ    AX, R10
	ADCQ    $0x00, R11
	MULXQ   40(BP), AX, BX
	ADDQ    AX, R11
	ADCQ    $0x00, BX
	ADDQ    16(SP), SI
	ADCQ    24(SP), DI
	ADCQ    32(SP), R8
	ADCQ    40(SP), R9
	ADCQ    48(SP), R10
	ADCQ    56(SP), R11
	ADCQ    $0x00, BX
	MOVQ    BX, 64(SP)
	MOVQ    SI, 16(SP)
	MOVQ    DI, 24(SP)
	MOVQ    R8, 32(SP)
	MOVQ    R9, 40(SP)
	MOVQ    R10, 48(SP)
	MOVQ    R11, 56(SP)
	MOVQ    24(CX), DX
	MULXQ   (BP), SI, DI
	MULXQ   8(BP), AX, R8
	ADDQ    AX, DI
	ADCQ    $0x00, R8
	MULXQ   16(BP), AX, R9
	ADDQ    AX, R8
	ADCQ    $0x00, R9
	MULXQ   24(BP), AX, R10
	ADDQ    AX, R9
	ADCQ    $0x00, R10
	MULXQ   32(BP), AX, R11
	ADDQ    AX, R10
	ADCQ    $0x00, R11
	MULXQ   40(BP), AX, BX
	ADDQ    AX, R11
	ADCQ    $0x00, BX
	ADDQ    24(SP), SI
	ADCQ    32(SP), DI
	ADCQ    40(SP), R8
	ADCQ    48(SP), R9
	ADCQ    56(SP), R10
	ADCQ    64(SP), R11
	ADCQ    $0x00, BX
	MOVQ    BX, 72(SP)
	MOVQ    SI, 24(SP)
	MOVQ    DI, 32(SP)
	MOVQ    R8, 40(SP)
	MOVQ    R9, 48(SP)
	MOVQ    R10, 56(SP)
	MOVQ    R11, 64(SP)
	MOVQ    32(CX), DX
	MULXQ   (BP), SI, DI
	MULXQ   8(BP), AX, R8
	ADDQ    AX, DI
	ADCQ    $0x00, R8
	MULXQ   16(BP), AX, R9
	ADDQ    AX, R8
	ADCQ    $0x00, R9
	MULXQ   24(BP), AX, R10
	ADDQ    AX, R9
	ADCQ    $0x00, R10
	MULXQ   32(BP), AX, R11
	ADDQ    AX, R10
	ADCQ    $0x00, R11
	MULXQ   40(BP), AX, BX
	ADDQ    AX, R11
	ADCQ    $0x00, BX
	ADDQ    32(SP), SI
	ADCQ    40(SP), DI
	ADCQ    48(SP), R8
	ADCQ    56(SP), R9
	ADCQ    64(SP), R10
	ADCQ    72(SP), R11
	ADCQ    $0x00, BX
	MOVQ    BX, 80(SP)
	MOVQ    SI, 32(SP)
	MOVQ    DI, 40(SP)
	MOVQ    R8, 48(SP)
	MOVQ    R9, 56(SP)
	MOVQ    R10, 64(SP)
	MOVQ    R11, 72(SP)
	MOVQ    40(CX), DX
	MULXQ   (BP), SI, DI
	MULXQ   8(BP), AX, R8
	ADDQ    AX, DI
	ADCQ    $0x00, R8
	MULXQ   16(BP), AX, R9
	ADDQ    AX, R8
	ADCQ    $0x00, R9
	MULXQ   24(BP), AX, R10
	ADDQ    AX, R9
	ADCQ    $0x00, R10
	MULXQ   32(BP), AX, R11
	ADDQ    AX, R10
	ADCQ    $0x00, R11
	MULXQ   40(BP), AX, BX
	ADDQ    AX, R11
	ADCQ    $0x00, BX
	ADDQ    40(SP), SI
	ADCQ    48(SP), DI
	ADCQ    56(SP), R8
	ADCQ    64(SP), R9
	ADCQ    72(SP), R10
	ADCQ    80(SP), R11
	ADCQ    $0x00, BX
	MOVQ    BX, 88(SP)
	MOVQ    SI, 40(SP)
	MOVQ    DI, 48(SP)
	MOVQ    R8, 56(SP)
	MOVQ    R9, 64(SP)
	MOVQ    R10, 72(SP)
	MOVQ    R11, 80(SP)
	XORQ    R12, R12
	MOVQ    $0x89f3fffcfffcfffd, DX
	MULXQ   (SP), DX, AX
	MULXQ   ·q64+0(SB), SI, DI
	MULXQ   ·q64+8(SB), AX, R8
	ADDQ    AX, DI
	ADCQ    $0x00, R8
	MULXQ   ·q64+16(SB), AX, R9
	ADDQ    AX, R8
	ADCQ    $0x00, R9
	MULXQ   ·q64+24(SB), AX, R10
	ADDQ    AX, R9
	ADCQ    $0x00, R10
	MULXQ   ·q64+32(SB), AX, R11
	ADDQ    AX, R10
	ADCQ    $0x00, R11
	MULXQ   ·q64+40(SB), AX, BX
	ADDQ    AX, R11
	ADCQ    $0x00, BX
	ADDQ    (SP), SI
	ADCQ    8(SP), DI
	ADCQ    16(SP), R8
	ADCQ    24(SP), R9
	ADCQ    32(SP), R10
	ADCQ    40(SP), R11
	ADCQ    $0x00, BX
	ADDQ    R12, BX
	XORQ    R12, R12
	ADDQ    48(SP), BX
	ADCQ    $0x00, R12
	MOVQ    BX, 48(SP)
	MOVQ    DI, 8(SP)
	MOVQ    R8, 16(SP)
	MOVQ    R9, 24(SP)
	MOVQ    R10, 32(SP)
	MOVQ    R11, 40(SP)
	MOVQ    $0x89f3fffcfffcfffd, DX
	MULXQ   8(SP), DX, AX
	MULXQ   ·q64+0(SB), SI, DI
	MULXQ   ·q64+8(SB), AX, R8
	ADDQ    AX, DI
	ADCQ    $0x00, R8
	MULXQ   ·q64+16(SB), AX, R9
	ADDQ    AX, R8
	ADCQ    $0x00, R9
	MULXQ   ·q64+24(SB), AX, R10
	ADDQ    AX, R9
	ADCQ    $0x00, R10
	MULXQ   ·q64+32(SB), AX, R11
	ADDQ    AX, R10
	ADCQ    $0x00, R11
	MULXQ   ·q64+40(SB), AX, BX
	ADDQ    AX, R11
	ADCQ    $0x00, BX
	ADDQ    8(SP), SI
	ADCQ    16(SP), DI
	ADCQ    24(SP), R8
	ADCQ    32(SP), R9
	ADCQ    40(SP), R10
	ADCQ    48(SP), R11
	ADCQ    $0x00, BX
	ADDQ    R12, BX
	XORQ    R12, R12
	ADDQ    56(SP), BX
	ADCQ    $0x00, R12
	MOVQ    BX, 56(SP)
	MOVQ    DI, 16(SP)
	MOVQ    R8, 24(SP)
	MOVQ    R9, 32(SP)
	MOVQ    R10, 40(SP)
	MOVQ    R11, 48(SP)
	MOVQ    $0x89f3fffcfffcfffd, DX
	MULXQ   16(SP), DX, AX
	MULXQ   ·q64+0(SB), SI, DI
	MULXQ   ·q64+8(SB), AX, R8
	ADDQ    AX, DI
	ADCQ    $0x00, R8
	MULXQ   ·q64+16(SB), AX, R9
	ADDQ    AX, R8
	ADCQ    $0x00, R9
	MULXQ   ·q64+24(SB), AX, R10
	ADDQ    AX, R9
	ADCQ    $0x00, R10
	MULXQ   ·q64+32(SB), AX, R11
	ADDQ    AX, R10
	ADCQ    $0x00, R11
	MULXQ   ·q64+40(SB), AX, BX
	ADDQ    AX, R11
	ADCQ    $0x00, BX
	ADDQ    16(SP), SI
	ADCQ    24(SP), DI
	ADCQ    32(SP), R8
	ADCQ    40(SP), R9
	ADCQ    48(SP), R10
	ADCQ    56(SP), R11
	ADCQ    $0x00, BX
	ADDQ    R12, BX
	XORQ    R12, R12
	ADDQ    64(SP), BX
	ADCQ    $0x00, R12
	MOVQ    BX, 64(SP)
	MOVQ    DI, 24(SP)
	MOVQ    R8, 32(SP)
	MOVQ    R9, 40(SP)
	MOVQ    R10, 48(SP)
	MOVQ    R11, 56(SP)
	MOVQ    $0x89f3fffcfffcfffd, DX
	MULXQ   24(SP), DX, AX
	MULXQ   ·q64+0(SB), SI, DI
	MULXQ   ·q64+8(SB), AX, R8
	ADDQ    AX, DI
	ADCQ    $0x00, R8
	MULXQ   ·q64+16(SB), AX, R9
	ADDQ    AX, R8
	ADCQ    $0x00, R9
	MULXQ   ·q64+24(SB), AX, R10
	ADDQ    AX, R9
	ADCQ    $0x00, R10
	MULXQ   ·q64+32(SB), AX, R11
	ADDQ    AX, R10
	ADCQ    $0x00, R11
	MULXQ   ·q64+40(SB), AX, BX
	ADDQ    AX, R11
	ADCQ    $0x00, BX
	ADDQ    24(SP), SI
	ADCQ    32(SP), DI
	ADCQ    40(SP), R8
	ADCQ    48(SP), R9
	ADCQ    56(SP), R10
	ADCQ    64(SP), R11
	ADCQ    $0x00, BX
	ADDQ    R12, BX
	XORQ    R12, R12
	ADDQ    72(SP), BX
	ADCQ    $0x00, R12
	MOVQ    BX, 72(SP)
	MOVQ    DI, 32(SP)
	MOVQ    R8, 40(SP)
	MOVQ    R9, 48(SP)
	MOVQ    R10, 56(SP)
	MOVQ    R11, 64(SP)
	MOVQ    $0x89f3fffcfffcfffd, DX
	MULXQ   32(SP), DX, AX
	MULXQ   ·q64+0(SB), SI, DI
	MULXQ   ·q64+8(SB), AX, R8
	ADDQ    AX, DI
	ADCQ    $0x00, R8
	MULXQ   ·q64+16(SB), AX, R9
	ADDQ    AX, R8
	ADCQ    $0x00, R9
	MULXQ   ·q64+24(SB), AX, R10
	ADDQ    AX, R9
	ADCQ    $0x00, R10
	MULXQ   ·q64+32(SB), AX, R11
	ADDQ    AX, R10
	ADCQ    $0x00, R11
	MULXQ   ·q64+40(SB), AX, BX
	ADDQ    AX, R11
	ADCQ    $0x00, BX
	ADDQ    32(SP), SI
	ADCQ    40(SP), DI
	ADCQ    48(SP), R8
	ADCQ    56(SP), R9
	ADCQ    64(SP), R10
	ADCQ    72(SP), R11
	ADCQ    $0x00, BX
	ADDQ    R12, BX
	XORQ    R12, R12
	ADDQ    80(SP), BX
	ADCQ    $0x00, R12
	MOVQ    BX, 80(SP)
	MOVQ    DI, 40(SP)
	MOVQ    R8, 48(SP)
	MOVQ    R9, 56(SP)
	MOVQ    R10, 64(SP)
	MOVQ    R11, 72(SP)
	MOVQ    $0x89f3fffcfffcfffd, DX
	MULXQ   40(SP), DX, AX
	MULXQ   ·q64+0(SB), SI, DI
	MULXQ   ·q64+8(SB), AX, R8
	ADDQ    AX, DI
	ADCQ    $0x00, R8
	MULXQ   ·q64+16(SB), AX, R9
	ADDQ    AX, R8
	ADCQ    $0x00, R9
	MULXQ   ·q64+24(SB), AX, R10
	ADDQ    AX, R9
	ADCQ    $0x00, R10
	MULXQ   ·q64+32(SB), AX, R11
	ADDQ    AX, R10
	ADCQ    $0x00, R11
	MULXQ   ·q64+40(SB), AX, BX
	ADDQ    AX, R11
	ADCQ    $0x00, BX
	ADDQ    40(SP), SI
	ADCQ    48(SP), DI
	ADCQ    56(SP), R8
	ADCQ    64(SP), R9
	ADCQ    72(SP), R10
	ADCQ    80(SP), R11
	ADCQ    $0x00, BX
	ADDQ    R12, BX
	XORQ    R12, R12
	ADDQ    88(SP), BX
	ADCQ    $0x00, R12
	MOVQ    BX, 88(SP)
	MOVQ    DI, 48(SP)
	MOVQ    R8, 56(SP)
	MOVQ    R9, 64(SP)
	MOVQ    R10, 72(SP)
	MOVQ    R11, 80(SP)
	MOVQ    48(SP), SI
	MOVQ    56(SP), DI
	MOVQ    64(SP), R8
	MOVQ    72(SP), R9
	MOVQ    80(SP), R10
	MOVQ    88(SP), R11
	MOVQ    SI, AX
	MOVQ    DI, CX
	MOVQ    R8, DX
	MOVQ    R9, BX
	MOVQ    R10, BP
	MOVQ    R11, R12
	SUBQ    ·q64+0(SB), AX
	SBBQ    ·q64+8(SB), CX
	SBBQ    ·q64+16(SB), DX
	SBBQ    ·q64+24(SB), BX
	SBBQ    ·q64+32(SB), BP
	SBBQ    ·q64+40(SB), R12
	CMOVQCC AX, SI
	CMOVQCC CX, DI
	CMOVQCC DX, R8
	CMOVQCC BX, R9
	CMOVQCC BP, R10
	CMOVQCC R12, R11
	JMP     out

fallback:
	MOVQ    (CX), AX
	MULQ    (BP)
	MOVQ    AX, SI
	MOVQ    DX, DI
	MOVQ    (CX), AX
	MULQ    8(BP)
	ADDQ    AX, DI
	ADCQ    $0x00, DX
	MOVQ    DX, R8
	MOVQ    (CX), AX
	MULQ    16(BP)
	ADDQ    AX, R8
	ADCQ    $0x00, DX
	MOVQ    DX, R9
	MOVQ    (CX), AX
	MULQ    24(BP)
	ADDQ    AX, R9
	ADCQ    $0x00, DX
	MOVQ    DX, R10
	MOVQ    (CX), AX
	MULQ    32(BP)
	ADDQ    AX, R10
	ADCQ    $0x00, DX
	MOVQ    DX, R11
	MOVQ    (CX), AX
	MULQ    40(BP)
	ADDQ    AX, R11
	ADCQ    $0x00, DX
	MOVQ    DX, 48(SP)
	MOVQ    SI, (SP)
	MOVQ    DI, 8(SP)
	MOVQ    R8, 16(SP)
	MOVQ    R9, 24(SP)
	MOVQ    R10, 32(SP)
	MOVQ    R11, 40(SP)
	MOVQ    8(CX), AX
	MULQ    (BP)
	MOVQ    AX, SI
	MOVQ    DX, DI
	MOVQ    8(CX), AX
	MULQ    8(BP)
	ADDQ    AX, DI
	ADCQ    $0x00, DX
	MOVQ    DX, R8
	MOVQ    8(CX), AX
	MULQ    16(BP)
	ADDQ    AX, R8
	ADCQ    $0x00, DX
	MOVQ    DX, R9
	MOVQ    8(CX), AX
	MULQ    24(BP)
	ADDQ    AX, R9
	ADCQ    $0x00, DX
	MOVQ    DX, R10
	MOVQ    8(CX), AX
	MULQ    32(BP)
	ADDQ    AX, R10
	ADCQ    $0x00, DX
	MOVQ    DX, R11
	MOVQ    8(CX), AX
	MULQ    40(BP)
	ADDQ    AX, R11
	ADCQ    $0x00, DX
	ADDQ    8(SP), SI
	ADCQ    16(SP), DI
	ADCQ    24(SP), R8
	ADCQ    32(SP), R9
	ADCQ    40(SP), R10
	ADCQ    48(SP), R11
	ADCQ    $0x00, DX
	MOVQ    DX, 56(SP)
	MOVQ    SI, 8(SP)
	MOVQ    DI, 16(SP)
	MOVQ    R8, 24(SP)
	MOVQ    R9, 32(SP)
	MOVQ    R10, 40(SP)
	MOVQ    R11, 48(SP)
	MOVQ    16(CX), AX
	MULQ    (BP)
	MOVQ    AX, SI
	MOVQ    DX, DI
	MOVQ    16(CX), AX
	MULQ    8(BP)
	ADDQ    AX, DI
	ADCQ    $0x00, DX
	MOVQ    DX, R8
	MOVQ    16(CX), AX
	MULQ    16(BP)
	ADDQ    AX, R8
	ADCQ    $0x00, DX
	MOVQ    DX, R9
	MOVQ    16(CX), AX
	MULQ    24(BP)
	ADDQ    AX, R9
	ADCQ    $0x00, DX
	MOVQ    DX, R10
	MOVQ    16(CX), AX
	MULQ    32(BP)
	ADDQ    AX, R10
	ADCQ    $0x00, DX
	MOVQ    DX, R11
	MOVQ    16(CX), AX
	MULQ    40(BP)
	ADDQ    AX, R11
	ADCQ    $0x00, DX
	ADDQ    16(SP), SI
	ADCQ    24(SP), DI
	ADCQ    32(SP), R8
	ADCQ    40(SP), R9
	ADCQ    48(SP), R10
	ADCQ    56(SP), R11
	ADCQ    $0x00, DX
	MOVQ    DX, 64(SP)
	MOVQ    SI, 16(SP)
	MOVQ    DI, 24(SP)
	MOVQ    R8, 32(SP)
	MOVQ    R9, 40(SP)
	MOVQ    R10, 48(SP)
	MOVQ    R11, 56(SP)
	MOVQ    24(CX), AX
	MULQ    (BP)
	MOVQ    AX, SI
	MOVQ    DX, DI
	MOVQ    24(CX), AX
	MULQ    8(BP)
	ADDQ    AX, DI
	ADCQ    $0x00, DX
	MOVQ    DX, R8
	MOVQ    24(CX), AX
	MULQ    16(BP)
	ADDQ    AX, R8
	ADCQ    $0x00, DX
	MOVQ    DX, R9
	MOVQ    24(CX), AX
	MULQ    24(BP)
	ADDQ    AX, R9
	ADCQ    $0x00, DX
	MOVQ    DX, R10
	MOVQ    24(CX), AX
	MULQ    32(BP)
	ADDQ    AX, R10
	ADCQ    $0x00, DX
	MOVQ    DX, R11
	MOVQ    24(CX), AX
	MULQ    40(BP)
	ADDQ    AX, R11
	ADCQ    $0x00, DX
	ADDQ    24(SP), SI
	ADCQ    32(SP), DI
	ADCQ    40(SP), R8
	ADCQ    48(SP), R9
	ADCQ    56(SP), R10
	ADCQ    64(SP), R11
	ADCQ    $0x00, DX
	MOVQ    DX, 72(SP)
	MOVQ    SI, 24(SP)
	MOVQ    DI, 32(SP)
	MOVQ    R8, 40(SP)
	MOVQ    R9, 48(SP)
	MOVQ    R10, 56(SP)
	MOVQ    R11, 64(SP)
	MOVQ    32(CX), AX
	MULQ    (BP)
	MOVQ    AX, SI
	MOVQ    DX, DI
	MOVQ    32(CX), AX
	MULQ    8(BP)
	ADDQ    AX, DI
	ADCQ    $0x00, DX
	MOVQ    DX, R8
	MOVQ    32(CX), AX
	MULQ    16(BP)
	ADDQ    AX, R8
	ADCQ    $0x00, DX
	MOVQ    DX, R9
	MOVQ    32(CX), AX
	MULQ    24(BP)
	ADDQ    AX, R9
	ADCQ    $0x00, DX
	MOVQ    DX, R10
	MOVQ    32(CX), AX
	MULQ    32(BP)
	ADDQ    AX, R10
	ADCQ    $0x00, DX
	MOVQ    DX, R11
	MOVQ    32(CX), AX
	MULQ    40(BP)
	ADDQ    AX, R11
	ADCQ    $0x00, DX
	ADDQ    32(SP), SI
	ADCQ    40(SP), DI
	ADCQ    48(SP), R8
	ADCQ    56(SP), R9
	ADCQ    64(SP), R10
	ADCQ    72(SP), R11
	ADCQ    $0x00, DX
	MOVQ    DX, 80(SP)
	MOVQ    SI, 32(SP)
	MOVQ    DI, 40(SP)
	MOVQ    R8, 48(SP)
	MOVQ    R9, 56(SP)
	MOVQ    R10, 64(SP)
	MOVQ    R11, 72(SP)
	MOVQ    40(CX), AX
	MULQ    (BP)
	MOVQ    AX, SI
	MOVQ    DX, DI
	MOVQ    40(CX), AX
	MULQ    8(BP)
	ADDQ    AX, DI
	ADCQ    $0x00, DX
	MOVQ    DX, R8
	MOVQ    40(CX), AX
	MULQ    16(BP)
	ADDQ    AX, R8
	ADCQ    $0x00, DX
	MOVQ    DX, R9
	MOVQ    40(CX), AX
	MULQ    24(BP)
	ADDQ    AX, R9
	ADCQ    $0x00, DX
	MOVQ    DX, R10
	MOVQ    40(CX), AX
	MULQ    32(BP)
	ADDQ    AX, R10
	ADCQ    $0x00, DX
	MOVQ    DX, R11
	MOVQ    40(CX), AX
	MULQ    40(BP)
	ADDQ    AX, R11
	ADCQ    $0x00, DX
	ADDQ    40(SP), SI
	ADCQ    48(SP), DI
	ADCQ    56(SP), R8
	ADCQ    64(SP), R9
	ADCQ    72(SP), R10
	ADCQ    80(SP), R11
	ADCQ    $0x00, DX
	MOVQ    DX, 88(SP)
	MOVQ    SI, 40(SP)
	MOVQ    DI, 48(SP)
	MOVQ    R8, 56(SP)
	MOVQ    R9, 64(SP)
	MOVQ    R10, 72(SP)
	MOVQ    R11, 80(SP)
	XORQ    R12, R12
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    (SP)
	MULQ    ·q64+0(SB)
	MOVQ    AX, SI
	MOVQ    DX, DI
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    (SP)
	MULQ    ·q64+8(SB)
	ADDQ    AX, DI
	ADCQ    $0x00, DX
	MOVQ    DX, R8
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    (SP)
	MULQ    ·q64+16(SB)
	ADDQ    AX, R8
	ADCQ    $0x00, DX
	MOVQ    DX, R9
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    (SP)
	MULQ    ·q64+24(SB)
	ADDQ    AX, R9
	ADCQ    $0x00, DX
	MOVQ    DX, R10
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    (SP)
	MULQ    ·q64+32(SB)
	ADDQ    AX, R10
	ADCQ    $0x00, DX
	MOVQ    DX, R11
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    (SP)
	MULQ    ·q64+40(SB)
	ADDQ    AX, R11
	ADCQ    $0x00, DX
	MOVQ    DX, AX
	ADDQ    (SP), SI
	ADCQ    8(SP), DI
	ADCQ    16(SP), R8
	ADCQ    24(SP), R9
	ADCQ    32(SP), R10
	ADCQ    40(SP), R11
	ADCQ    $0x00, AX
	ADDQ    R12, AX
	XORQ    R12, R12
	ADDQ    48(SP), AX
	ADCQ    $0x00, R12
	MOVQ    AX, 48(SP)
	MOVQ    DI, 8(SP)
	MOVQ    R8, 16(SP)
	MOVQ    R9, 24(SP)
	MOVQ    R10, 32(SP)
	MOVQ    R11, 40(SP)
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    8(SP)
	MULQ    ·q64+0(SB)
	MOVQ    AX, SI
	MOVQ    DX, DI
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    8(SP)
	MULQ    ·q64+8(SB)
	ADDQ    AX, DI
	ADCQ    $0x00, DX
	MOVQ    DX, R8
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    8(SP)
	MULQ    ·q64+16(SB)
	ADDQ    AX, R8
	ADCQ    $0x00, DX
	MOVQ    DX, R9
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    8(SP)
	MULQ    ·q64+24(SB)
	ADDQ    AX, R9
	ADCQ    $0x00, DX
	MOVQ    DX, R10
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    8(SP)
	MULQ    ·q64+32(SB)
	ADDQ    AX, R10
	ADCQ    $0x00, DX
	MOVQ    DX, R11
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    8(SP)
	MULQ    ·q64+40(SB)
	ADDQ    AX, R11
	ADCQ    $0x00, DX
	MOVQ    DX, AX
	ADDQ    8(SP), SI
	ADCQ    16(SP), DI
	ADCQ    24(SP), R8
	ADCQ    32(SP), R9
	ADCQ    40(SP), R10
	ADCQ    48(SP), R11
	ADCQ    $0x00, AX
	ADDQ    R12, AX
	XORQ    R12, R12
	ADDQ    56(SP), AX
	ADCQ    $0x00, R12
	MOVQ    AX, 56(SP)
	MOVQ    DI, 16(SP)
	MOVQ    R8, 24(SP)
	MOVQ    R9, 32(SP)
	MOVQ    R10, 40(SP)
	MOVQ    R11, 48(SP)
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    16(SP)
	MULQ    ·q64+0(SB)
	MOVQ    AX, SI
	MOVQ    DX, DI
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    16(SP)
	MULQ    ·q64+8(SB)
	ADDQ    AX, DI
	ADCQ    $0x00, DX
	MOVQ    DX, R8
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    16(SP)
	MULQ    ·q64+16(SB)
	ADDQ    AX, R8
	ADCQ    $0x00, DX
	MOVQ    DX, R9
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    16(SP)
	MULQ    ·q64+24(SB)
	ADDQ    AX, R9
	ADCQ    $0x00, DX
	MOVQ    DX, R10
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    16(SP)
	MULQ    ·q64+32(SB)
	ADDQ    AX, R10
	ADCQ    $0x00, DX
	MOVQ    DX, R11
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    16(SP)
	MULQ    ·q64+40(SB)
	ADDQ    AX, R11
	ADCQ    $0x00, DX
	MOVQ    DX, AX
	ADDQ    16(SP), SI
	ADCQ    24(SP), DI
	ADCQ    32(SP), R8
	ADCQ    40(SP), R9
	ADCQ    48(SP), R10
	ADCQ    56(SP), R11
	ADCQ    $0x00, AX
	ADDQ    R12, AX
	XORQ    R12, R12
	ADDQ    64(SP), AX
	ADCQ    $0x00, R12
	MOVQ    AX, 64(SP)
	MOVQ    DI, 24(SP)
	MOVQ    R8, 32(SP)
	MOVQ    R9, 40(SP)
	MOVQ    R10, 48(SP)
	MOVQ    R11, 56(SP)
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    24(SP)
	MULQ    ·q64+0(SB)
	MOVQ    AX, SI
	MOVQ    DX, DI
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    24(SP)
	MULQ    ·q64+8(SB)
	ADDQ    AX, DI
	ADCQ    $0x00, DX
	MOVQ    DX, R8
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    24(SP)
	MULQ    ·q64+16(SB)
	ADDQ    AX, R8
	ADCQ    $0x00, DX
	MOVQ    DX, R9
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    24(SP)
	MULQ    ·q64+24(SB)
	ADDQ    AX, R9
	ADCQ    $0x00, DX
	MOVQ    DX, R10
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    24(SP)
	MULQ    ·q64+32(SB)
	ADDQ    AX, R10
	ADCQ    $0x00, DX
	MOVQ    DX, R11
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    24(SP)
	MULQ    ·q64+40(SB)
	ADDQ    AX, R11
	ADCQ    $0x00, DX
	MOVQ    DX, AX
	ADDQ    24(SP), SI
	ADCQ    32(SP), DI
	ADCQ    40(SP), R8
	ADCQ    48(SP), R9
	ADCQ    56(SP), R10
	ADCQ    64(SP), R11
	ADCQ    $0x00, AX
	ADDQ    R12, AX
	XORQ    R12, R12
	ADDQ    72(SP), AX
	ADCQ    $0x00, R12
	MOVQ    AX, 72(SP)
	MOVQ    DI, 32(SP)
	MOVQ    R8, 40(SP)
	MOVQ    R9, 48(SP)
	MOVQ    R10, 56(SP)
	MOVQ    R11, 64(SP)
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    32(SP)
	MULQ    ·q64+0(SB)
	MOVQ    AX, SI
	MOVQ    DX, DI
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    32(SP)
	MULQ    ·q64+8(SB)
	ADDQ    AX, DI
	ADCQ    $0x00, DX
	MOVQ    DX, R8
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    32(SP)
	MULQ    ·q64+16(SB)
	ADDQ    AX, R8
	ADCQ    $0x00, DX
	MOVQ    DX, R9
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    32(SP)
	MULQ    ·q64+24(SB)
	ADDQ    AX, R9
	ADCQ    $0x00, DX
	MOVQ    DX, R10
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    32(SP)
	MULQ    ·q64+32(SB)
	ADDQ    AX, R10
	ADCQ    $0x00, DX
	MOVQ    DX, R11
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    32(SP)
	MULQ    ·q64+40(SB)
	ADDQ    AX, R11
	ADCQ    $0x00, DX
	MOVQ    DX, AX
	ADDQ    32(SP), SI
	ADCQ    40(SP), DI
	ADCQ    48(SP), R8
	ADCQ    56(SP), R9
	ADCQ    64(SP), R10
	ADCQ    72(SP), R11
	ADCQ    $0x00, AX
	ADDQ    R12, AX
	XORQ    R12, R12
	ADDQ    80(SP), AX
	ADCQ    $0x00, R12
	MOVQ    AX, 80(SP)
	MOVQ    DI, 40(SP)
	MOVQ    R8, 48(SP)
	MOVQ    R9, 56(SP)
	MOVQ    R10, 64(SP)
	MOVQ    R11, 72(SP)
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    40(SP)
	MULQ    ·q64+0(SB)
	MOVQ    AX, SI
	MOVQ    DX, DI
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    40(SP)
	MULQ    ·q64+8(SB)
	ADDQ    AX, DI
	ADCQ    $0x00, DX
	MOVQ    DX, R8
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    40(SP)
	MULQ    ·q64+16(SB)
	ADDQ    AX, R8
	ADCQ    $0x00, DX
	MOVQ    DX, R9
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    40(SP)
	MULQ    ·q64+24(SB)
	ADDQ    AX, R9
	ADCQ    $0x00, DX
	MOVQ    DX, R10
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    40(SP)
	MULQ    ·q64+32(SB)
	ADDQ    AX, R10
	ADCQ    $0x00, DX
	MOVQ    DX, R11
	MOVQ    $0x89f3fffcfffcfffd, AX
	MULQ    40(SP)
	MULQ    ·q64+40(SB)
	ADDQ    AX, R11
	ADCQ    $0x00, DX
	MOVQ    DX, AX
	ADDQ    40(SP), SI
	ADCQ    48(SP), DI
	ADCQ    56(SP), R8
	ADCQ    64(SP), R9
	ADCQ    72(SP), R10
	ADCQ    80(SP), R11
	ADCQ    $0x00, AX
	ADDQ    R12, AX
	XORQ    R12, R12
	ADDQ    88(SP), AX
	ADCQ    $0x00, R12
	MOVQ    AX, 88(SP)
	MOVQ    DI, 48(SP)
	MOVQ    R8, 56(SP)
	MOVQ    R9, 64(SP)
	MOVQ    R10, 72(SP)
	MOVQ    R11, 80(SP)
	MOVQ    48(SP), SI
	MOVQ    56(SP), DI
	MOVQ    64(SP), R8
	MOVQ    72(SP), R9
	MOVQ    80(SP), R10
	MOVQ    88(SP), R11
	MOVQ    SI, AX
	MOVQ    DI, CX
	MOVQ    R8, DX
	MOVQ    R9, BX
	MOVQ    R10, BP
	MOVQ    R11, R12
	SUBQ    ·q64+0(SB), AX
	SBBQ    ·q64+8(SB), CX
	SBBQ    ·q64+16(SB), DX
	SBBQ    ·q64+24(SB), BX
	SBBQ    ·q64+32(SB), BP
	SBBQ    ·q64+40(SB), R12
	CMOVQCC AX, SI
	CMOVQCC CX, DI
	CMOVQCC DX, R8
	CMOVQCC BX, R9
	CMOVQCC BP, R10
	CMOVQCC R12, R11

out:
	MOVQ z+0(FP), CX
	MOVQ SI, (CX)
	MOVQ DI, 8(CX)
	MOVQ R8, 16(CX)
	MOVQ R9, 24(CX)
	MOVQ R10, 32(CX)
	MOVQ R11, 40(CX)
	RET
