// Code generated by command: go run asm.go -out ../../fq_amd64.s -stubs ../../fq_decl.go. DO NOT EDIT.

package fq

// fqAdd sets z to the sum x+y.
func fqAdd(z *[6]uint64, x *[6]uint64, y *[6]uint64)

// fqNeg sets z to -x.
func fqNeg(z *[6]uint64, x *[6]uint64)

// fqSub sets z to the difference x-y.
func fqSub(z *[6]uint64, x *[6]uint64, y *[6]uint64)

// fqMul sets z to the product x*y.
func fqMul(z *[6]uint64, x *[6]uint64, y *[6]uint64)
