// Code generated by command: go run asm.go -out ../../fr_amd64.s -stubs ../../fr_decl.go. DO NOT EDIT.

// func frAdd(z *[4]uint64, x *[4]uint64, y *[4]uint64)
TEXT ·frAdd(SB), $0-24
	MOVQ    x+8(FP), AX
	MOVQ    y+16(FP), CX
	MOVQ    (AX), DX
	MOVQ    8(AX), BX
	MOVQ    16(AX), BP
	MOVQ    24(AX), AX
	ADDQ    (CX), DX
	ADCQ    8(CX), BX
	ADCQ    16(CX), BP
	ADCQ    24(CX), AX
	MOVQ    z+0(FP), CX
	MOVQ    DX, SI
	MOVQ    BX, DI
	MOVQ    BP, R8
	MOVQ    AX, R9
	SUBQ    r64+0(SB), SI
	SBBQ    r64+8(SB), DI
	SBBQ    r64+16(SB), R8
	SBBQ    r64+24(SB), R9
	CMOVQCC SI, DX
	CMOVQCC DI, BX
	CMOVQCC R8, BP
	CMOVQCC R9, AX
	MOVQ    SI, (CX)
	MOVQ    DI, 8(CX)
	MOVQ    R8, 16(CX)
	MOVQ    R9, 24(CX)
	RET

// func frNeg(z *[4]uint64, x *[4]uint64)
TEXT ·frNeg(SB), $0-16
	MOVQ x+8(FP), AX
	MOVQ r64+0(SB), CX
	MOVQ r64+8(SB), DX
	MOVQ r64+16(SB), BX
	MOVQ r64+24(SB), BP
	SUBQ (AX), CX
	SBBQ 8(AX), DX
	SBBQ 16(AX), BX
	SBBQ 24(AX), BP
	MOVQ z+0(FP), AX
	MOVQ CX, (AX)
	MOVQ DX, 8(AX)
	MOVQ BX, 16(AX)
	MOVQ BP, 24(AX)

// func frSub(z *[4]uint64, x *[4]uint64, y *[4]uint64)
TEXT ·frSub(SB), $0-24
	MOVQ    y+16(FP), AX
	MOVQ    r64+0(SB), CX
	MOVQ    r64+8(SB), DX
	MOVQ    r64+16(SB), BX
	MOVQ    r64+24(SB), BP
	SUBQ    (AX), CX
	SBBQ    8(AX), DX
	SBBQ    16(AX), BX
	SBBQ    24(AX), BP
	MOVQ    x+8(FP), AX
	ADDQ    (AX), CX
	ADCQ    8(AX), DX
	ADCQ    16(AX), BX
	ADCQ    24(AX), BP
	MOVQ    z+0(FP), AX
	MOVQ    CX, SI
	MOVQ    DX, DI
	MOVQ    BX, R8
	MOVQ    BP, R9
	SUBQ    r64+0(SB), SI
	SBBQ    r64+8(SB), DI
	SBBQ    r64+16(SB), R8
	SBBQ    r64+24(SB), R9
	CMOVQCC SI, CX
	CMOVQCC DI, DX
	CMOVQCC R8, BX
	CMOVQCC R9, BP
	MOVQ    SI, (AX)
	MOVQ    DI, 8(AX)
	MOVQ    R8, 16(AX)
	MOVQ    R9, 24(AX)
	RET

// func frMul(z *[4]uint64, x *[4]uint64, y *[4]uint64)
TEXT ·frMul(SB), $0-24
	RET
