// Code generated by command: go run asm.go -out ../../fr_amd64.s -stubs ../../fr_decl.go. DO NOT EDIT.

package fr

// frAdd sets z to the sum x+y.
func frAdd(z *[4]uint64, x *[4]uint64, y *[4]uint64)

// frNeg sets z to -x.
func frNeg(z *[4]uint64, x *[4]uint64)

// frSub sets z to the difference x-y.
func frSub(z *[4]uint64, x *[4]uint64, y *[4]uint64)

// frMul sets z to the product x*y.
func frMul(z *[4]uint64, x *[4]uint64, y *[4]uint64)
